version: "3.7"

services:

  nginx:
    image: nginx:1.15.3-alpine
    ports:
      - ${NGINX_PORTS}
      - "4443:443"
    volumes:
      - ./${NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - certbot_data:/etc/letsencrypt:ro
      - certbot_verification:/var/www/letsencrypt:ro

  fileserver:
    image: nginx:1.15.3-alpine
    volumes:
      - ./fileserver/files:/www/data:ro
      - ./fileserver/nginx.conf:/etc/nginx/nginx.conf
  
  webhooks:
    build:
      context: ./webhooks
    env_file:
      - webhooks.env
    volumes:
      - ./data:/mnt/data
      - ./keys:/mnt/keys

  certbot:
    image: certbot/certbot
    entrypoint: ''
    command: echo "Hello"
    volumes:
      - ./logs/letsencrypt:/var/log/letsencrypt
      - certbot_verification:/var/www
      - certbot_data:/etc/letsencrypt

volumes:
  certbot_data:
  certbot_verification: