version: "3.7"

services:

  nginx:
    image: nginx:1.15.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/${NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - certbot_data:/etc/letsencrypt:ro
      - certbot_verification:/var/www/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx

  fileserver:
    image: nginx:1.15.3-alpine
    volumes:
      - ./data:/www/data:ro
      - ./fileserver/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/fileserver:/var/log/nginx
  
  webhooks:
    build:
      context: ./webhooks
    env_file:
      - webhooks.env
    volumes:
      - ./repos:/mnt/repos
      - ./keys:/mnt/keys

  certbot:
    image: certbot/certbot
    entrypoint: '' # this is here to override certbot entry
    command: echo "Hello"
    volumes:
      - ./logs/letsencrypt:/var/log/letsencrypt
      - certbot_verification:/var/www
      - certbot_data:/etc/letsencrypt

volumes:
  certbot_data:
  certbot_verification: