version: "3.7"

services:

  redis:
    image: redis:alpine

  db:
    image: postgres:10.5
    volumes:
    - db-data:/var/lib/postgresql/data

  sso:
    build:
      context: ./sso
    environment:
      NODE_ENV: production
    depends_on:
      - db
  


volumes:
  db-data:
